language: android

android:
  components:
    - build-tools-21.1.2
    - extra-android-m2repository
    - android-21
    - android-18
    - sys-img-armeabi-v7a-android-18

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "bbgUijBzc39gn73pZ81S9up+TiLLg7C3onDu1eTPEbg1l2CukpmImY07psl6kTBWqDNCg/0SIJ+21PLNB9gEmrLpcHL4lKy7Y2b381B1brFsY/byaZKGrFi05t61VJlfsPv0Jv6vc3ExEcxGcSvGFWYvxFegJInkj0e+Ft2tfA8="
    - secure: "VeoQsk3wmtwo3tvvir1sYtmxFVvkZyPy8ivKAurBdhypw64d8PABTBvlSYwW4LRKWXFpEChB3Bg85gwEKPXE6GynHKI5rUW2Tr1gjoFZoBEOmCQ63nRYjMlA5aiM76JPONeV4Okm62oZwx2V8UAppl2NOce+sv59htBsjdmX1Pk="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
